# Generated by Django 5.0.3 on 2024-03-07 07:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=20)),
                ('vehicle_code', models.CharField(max_length=20)),
                ('gate_code', models.CharField(max_length=10)),
                ('order_code', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=20)),
                ('instock_time', models.DateTimeField(default=datetime.datetime(2024, 3, 7, 18, 20, 58, 532049), verbose_name='In-stock date')),
                ('outstock_time', models.DateTimeField(default=None, null=True, verbose_name='Out-stock date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_time', models.DateTimeField(default=datetime.datetime(2024, 3, 7, 18, 20, 58, 533072))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_time', models.DateTimeField(default=datetime.datetime(2024, 3, 7, 18, 20, 58, 533072), verbose_name='Order date')),
                ('status_code', models.CharField(max_length=2)),
                ('sku_code', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.transaction')),
            ],
        ),
    ]
